// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_own_20_fish_at_once = "CgkIz5b31I0aEAIQAQ"; // <GPGSID>
        public const string achievement_sans_is_waiting_offshore = "CgkIz5b31I0aEAIQBw"; // <GPGSID>
        public const string achievement_own_10_fish_at_once = "CgkIz5b31I0aEAIQAA"; // <GPGSID>
        public const string achievement_the_reaper_rises = "CgkIz5b31I0aEAIQBg"; // <GPGSID>
        public const string achievement_its_brock_from_pewter_city = "CgkIz5b31I0aEAIQCw"; // <GPGSID>
        public const string achievement_the_fish_mogul = "CgkIz5b31I0aEAIQDg"; // <GPGSID>
        public const string achievement_bruh_you_gonna_let_your_fish_die_like_that = "CgkIz5b31I0aEAIQAg"; // <GPGSID>
        public const string achievement_you_monster = "CgkIz5b31I0aEAIQBQ"; // <GPGSID>
        public const string achievement_cluttered = "CgkIz5b31I0aEAIQCg"; // <GPGSID>
        public const string leaderboard_fish_bred = "CgkIz5b31I0aEAIQDA"; // <GPGSID>
        public const string leaderboard_fish_in_tank = "CgkIz5b31I0aEAIQDQ"; // <GPGSID>
        public const string achievement_no_need_to_overfeed = "CgkIz5b31I0aEAIQAw"; // <GPGSID>
        public const string leaderboard_money_money_money_moneeyyy_monaayyy = "CgkIz5b31I0aEAIQCA"; // <GPGSID>
        public const string achievement_getting_wood = "CgkIz5b31I0aEAIQBA"; // <GPGSID>

}

